### ISSUE TITLE
Miss the "Secrets" class

### ISSUE THREAD

**Issue by johnwatsondev** [colintheshots/AnDevCon-RxPatterns#1]
Here is the SNAP_SHOT.
<img width="692" alt="qq20150812-2" src="https://cloud.githubusercontent.com/assets/12760754/9218556/f7634528-4105-11e5-87d6-a374f254795c.png">

Thanks in advance for fix this issue!

**Comment by colintheshots** [comment]
The Secrets class is in my .gitignore file since it simply contains a list
of static variables set to my API tokens. I didn't want to hand out my API
tokens to everyone, since it would grant them write access to my
repositories as me. You can create your own Secrets class with a String defined
using that variable name and set it equal to your Github personal access
token.

https://help.github.com/articles/creating-an-access-token-for-command-line-use/
