### ISSUE TITLE
Want to learn Example4.

### ISSUE THREAD

**Issue by minhoryang** [colintheshots/AnDevCon-RxPatterns#2]
Thank you for the great examples!
During the learning, I noticed that Example 4 was missing (for the live coding?)
So, could you please add the example4.

**Comment by colintheshots** [comment]
I planned an Example4, but then incorporated the ideas into Example3.

Essentially, you can put the code from doInBackground into the OnSubscribe
function of Observable.create(). OnPostExecute is equivalent to
subscribe(). Be sure to set schedulers so that onSubscribe() uses a
background thread scheduler and onObserve() uses Android's main thread
scheduler. You can execute operations before or after any part of the work
with the doOnLifecycle methods like doOnNext, doOnError, etc
